version: '3.8'

services:
  # Frontend - React Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rwh-network

  # Backend API (placeholder - implement as needed)
  backend:
    # Replace with your backend image
    image: node:18-alpine
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/rwhdb
    # volumes:
    #   - ./backend:/app
    # command: ["node", "server.js"]
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - rwh-network

  # Database (PostgreSQL example)
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rwhdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - rwh-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - rwh-network

volumes:
  postgres_data:

networks:
  rwh-network:
    driver: bridge
